version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dp_postgres
    environment:
      POSTGRES_USER: dp_admin
      POSTGRES_PASSWORD: dp_password
      POSTGRES_DB: delight_pack
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
